//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterileEntity
{
    using System;
    
    
    public sealed class MaterielPDAEntity
    {
        
        private int _idx;
        
        private string _pda001;
        
        private string _pda002;
        
        private string _pda003;
        
        private int _pda004;
        
        private string _pda005;
        
        private decimal _pda006;
        
        private string _pda007;
        
        private decimal _pda008;
        
        private decimal _pda009;
        
        private decimal _pda010;
        
        private string _pda011;
        
        private decimal _pda012;
        
        private decimal _pda013;
        
        private decimal _pda014;
        
        private int _pda015;
        
        private string _pda016;
        
        private decimal _pda017;
        
        private string _pda018;
        
        private string _pda019;
        
        private string _pda020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 合同号
        /// </summary>

        public string PDA001
        {
            get
            {
                return this._pda001;
            }
            set
            {
                this._pda001 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PDA002
        {
            get
            {
                return this._pda002;
            }
            set
            {
                this._pda002 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string PDA003
        {
            get
            {
                return this._pda003;
            }
            set
            {
                this._pda003 = value;
            }
        }

        /// <summary>
        /// 数量
        /// </summary>

        public int PDA004
        {
            get
            {
                return this._pda004;
            }
            set
            {
                this._pda004 = value;
            }
        }

        /// <summary>
        /// 单位
        /// </summary>

        public string PDA005
        {
            get
            {
                return this._pda005;
            }
            set
            {
                this._pda005 = value;
            }
        }

        /// <summary>
        /// 单价
        /// </summary>

        public decimal PDA006
        {
            get
            {
                return this._pda006;
            }
            set
            {
                this._pda006 = value;
            }
        }

        /// <summary>
        /// 托盘号
        /// </summary>

        public string PDA007
        {
            get
            {
                return this._pda007;
            }
            set
            {
                this._pda007 = value;
            }
        }

        /// <summary>
        /// 托盘规格长
        /// </summary>

        public decimal PDA008
        {
            get
            {
                return this._pda008;
            }
            set
            {
                this._pda008 = value;
            }
        }

        /// <summary>
        /// 托盘规格宽
        /// </summary>

        public decimal PDA009
        {
            get
            {
                return this._pda009;
            }
            set
            {
                this._pda009 = value;
            }
        }

        /// <summary>
        /// 托盘规格高
        /// </summary>

        public decimal PDA010
        {
            get
            {
                return this._pda010;
            }
            set
            {
                this._pda010 = value;
            }
        }

        /// <summary>
        /// 箱号
        /// </summary>

        public string PDA011
        {
            get
            {
                return this._pda011;
            }
            set
            {
                this._pda011 = value;
            }
        }

        /// <summary>
        /// 纸箱规格长
        /// </summary>

        public decimal PDA012
        {
            get
            {
                return this._pda012;
            }
            set
            {
                this._pda012 = value;
            }
        }

        /// <summary>
        /// 纸箱规格宽
        /// </summary>

        public decimal PDA013
        {
            get
            {
                return this._pda013;
            }
            set
            {
                this._pda013 = value;
            }
        }

        /// <summary>
        /// 纸箱规格高
        /// </summary>

        public decimal PDA014
        {
            get
            {
                return this._pda014;
            }
            set
            {
                this._pda014 = value;
            }
        }

        /// <summary>
        /// 每箱数量
        /// </summary>

        public int PDA015
        {
            get
            {
                return this._pda015;
            }
            set
            {
                this._pda015 = value;
            }
        }
        
        /// <summary>
        /// 规格
        /// </summary>
                 
        public string PDA016
        {
            get
            {
                return this._pda016;
            }
            set
            {
                this._pda016 = value;
            }
        }

        /// <summary>
        /// 每箱重量毛重
        /// </summary>

        public decimal PDA017
        {
            get
            {
                return this._pda017;
            }
            set
            {
                this._pda017 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string PDA018
        {
            get
            {
                return this._pda018;
            }
            set
            {
                this._pda018 = value;
            }
        }
        
        // 
        public string PDA019
        {
            get
            {
                return this._pda019;
            }
            set
            {
                this._pda019 = value;
            }
        }
        
        // 
        public string PDA020
        {
            get
            {
                return this._pda020;
            }
            set
            {
                this._pda020 = value;
            }
        }
    }
}
