//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterileEntity
{
    using System;
    
    
    public sealed class MaterielPDCEntity
    {
        
        private int _idx;
        
        private string _pdc001;
        
        private string _pdc002;
        
        private string _pdc003;
        
        private DateTime _pdc004;
        
        private string _pdc005;
        
        private string _pdc006;
        
        private string _pdc007;
        
        private string _pdc008;
        
        private string _pdc009;
        
        private string _pdc010;
        
        private string _pdc011;
        
        private string _pdc012;
        
        private string _pdc013;
        
        private string _pdc014;
        
        private string _pdc015;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PDC001
        {
            get
            {
                return this._pdc001;
            }
            set
            {
                this._pdc001 = value;
            }
        }

        /// <summary>
        /// 安全带款式
        /// </summary>

        public string PDC002
        {
            get
            {
                return this._pdc002;
            }
            set
            {
                this._pdc002 = value;
            }
        }

        /// <summary>
        /// 裁剪工艺
        /// </summary>

        public string PDC003
        {
            get
            {
                return this._pdc003;
            }
            set
            {
                this._pdc003 = value;
            }
        }
        
        // 
        public DateTime PDC004
        {
            get
            {
                return this._pdc004;
            }
            set
            {
                this._pdc004 = value;
            }
        }
        
        /// <summary>
        /// 合同号
        /// </summary>
                 
        public string PDC005
        {
            get
            {
                return this._pdc005;
            }
            set
            {
                this._pdc005 = value;
            }
        }
        
        // 
        public string PDC006
        {
            get
            {
                return this._pdc006;
            }
            set
            {
                this._pdc006 = value;
            }
        }
        
        // 
        public string PDC007
        {
            get
            {
                return this._pdc007;
            }
            set
            {
                this._pdc007 = value;
            }
        }
        
        // 
        public string PDC008
        {
            get
            {
                return this._pdc008;
            }
            set
            {
                this._pdc008 = value;
            }
        }
        
        // 
        public string PDC009
        {
            get
            {
                return this._pdc009;
            }
            set
            {
                this._pdc009 = value;
            }
        }
        
        // 
        public string PDC010
        {
            get
            {
                return this._pdc010;
            }
            set
            {
                this._pdc010 = value;
            }
        }
        
        // 
        public string PDC011
        {
            get
            {
                return this._pdc011;
            }
            set
            {
                this._pdc011 = value;
            }
        }
        
        // 
        public string PDC012
        {
            get
            {
                return this._pdc012;
            }
            set
            {
                this._pdc012 = value;
            }
        }
        
        // 
        public string PDC013
        {
            get
            {
                return this._pdc013;
            }
            set
            {
                this._pdc013 = value;
            }
        }
        
        // 
        public string PDC014
        {
            get
            {
                return this._pdc014;
            }
            set
            {
                this._pdc014 = value;
            }
        }
        
        // 
        public string PDC015
        {
            get
            {
                return this._pdc015;
            }
            set
            {
                this._pdc015 = value;
            }
        }
    }
}
