//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterileEntity
{
    using System;
    
    
    public sealed class MaterielPDUEntity
    {
        
        private int _idx;
        
        private string _pdu001;
        
        private string _pdu002;
        
        private string _pdu003;
        
        private string _pdu004;
        
        private string _pdu005;
        
        private string _pdu006;
        
        private string _pdu007;
        
        private string _pdu008;
        
        private string _pdu009;
        
        private string _pdu010;
        
        private string _pdu011;
        
        private string _pdu012;
        
        private string _pdu013;
        
        private string _pdu014;
        
        private string _pdu015;
        
        private DateTime? _pdu016;
        
        private string _pdu017;
        
        private string _pdu018;
        
        private string _pdu019;
        
        private string _pdu020;
        
        private string _pdu021;
        
        private string _pdu022;
        
        private string _pdu023;
        
        private string _pdu024;
        
        private string _pdu025;
        
        private string _pdu026;
        
        private string _pdu027;
        
        private string _pdu028;
        
        private string _pdu029;
        
        private string _pdu030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 合同编号
        /// </summary>

        public string PDU001
        {
            get
            {
                return this._pdu001;
            }
            set
            {
                this._pdu001 = value;
            }
        }

        /// <summary>
        /// 客人合同
        /// </summary>

        public string PDU002
        {
            get
            {
                return this._pdu002;
            }
            set
            {
                this._pdu002 = value;
            }
        }

        /// <summary>
        /// 客人编号
        /// </summary>

        public string PDU003
        {
            get
            {
                return this._pdu003;
            }
            set
            {
                this._pdu003 = value;
            }
        }

        /// <summary>
        /// 目的港口
        /// </summary>

        public string PDU004
        {
            get
            {
                return this._pdu004;
            }
            set
            {
                this._pdu004 = value;
            }
        }

        /// <summary>
        /// 参数
        /// </summary>

        public string PDU005
        {
            get
            {
                return this._pdu005;
            }
            set
            {
                this._pdu005 = value;
            }
        }

        /// <summary>
        /// 需方单位
        /// </summary>

        public string PDU006
        {
            get
            {
                return this._pdu006;
            }
            set
            {
                this._pdu006 = value;
            }
        }

        /// <summary>
        /// 负责人
        /// </summary>

        public string PDU007
        {
            get
            {
                return this._pdu007;
            }
            set
            {
                this._pdu007 = value;
            }
        }

        /// <summary>
        /// 通讯地址
        /// </summary>

        public string PDU008
        {
            get
            {
                return this._pdu008;
            }
            set
            {
                this._pdu008 = value;
            }
        }

        /// <summary>
        /// 电话
        /// </summary>

        public string PDU009
        {
            get
            {
                return this._pdu009;
            }
            set
            {
                this._pdu009 = value;
            }
        }

        /// <summary>
        /// 传真
        /// </summary>

        public string PDU010
        {
            get
            {
                return this._pdu010;
            }
            set
            {
                this._pdu010 = value;
            }
        }

        /// <summary>
        /// 供方单位
        /// </summary>

        public string PDU011
        {
            get
            {
                return this._pdu011;
            }
            set
            {
                this._pdu011 = value;
            }
        }

        /// <summary>
        /// 负责人
        /// </summary>

        public string PDU012
        {
            get
            {
                return this._pdu012;
            }
            set
            {
                this._pdu012 = value;
            }
        }

        /// <summary>
        /// 通讯地址
        /// </summary>

        public string PDU013
        {
            get
            {
                return this._pdu013;
            }
            set
            {
                this._pdu013 = value;
            }
        }

        /// <summary>
        /// 电话
        /// </summary>

        public string PDU014
        {
            get
            {
                return this._pdu014;
            }
            set
            {
                this._pdu014 = value;
            }
        }

        /// <summary>
        /// 传真
        /// </summary>

        public string PDU015
        {
            get
            {
                return this._pdu015;
            }
            set
            {
                this._pdu015 = value;
            }
        }

        /// <summary>
        /// 购销合同日期
        /// </summary>

        public DateTime? PDU016
        {
            get
            {
                return this._pdu016;
            }
            set
            {
                this._pdu016 = value;
            }
        }
        
        // 
        public string PDU017
        {
            get
            {
                return this._pdu017;
            }
            set
            {
                this._pdu017 = value;
            }
        }
        
        // 
        public string PDU018
        {
            get
            {
                return this._pdu018;
            }
            set
            {
                this._pdu018 = value;
            }
        }
        
        // 
        public string PDU019
        {
            get
            {
                return this._pdu019;
            }
            set
            {
                this._pdu019 = value;
            }
        }
        
        // 
        public string PDU020
        {
            get
            {
                return this._pdu020;
            }
            set
            {
                this._pdu020 = value;
            }
        }
        
        // 
        public string PDU021
        {
            get
            {
                return this._pdu021;
            }
            set
            {
                this._pdu021 = value;
            }
        }
        
        // 
        public string PDU022
        {
            get
            {
                return this._pdu022;
            }
            set
            {
                this._pdu022 = value;
            }
        }
        
        // 
        public string PDU023
        {
            get
            {
                return this._pdu023;
            }
            set
            {
                this._pdu023 = value;
            }
        }
        
        // 
        public string PDU024
        {
            get
            {
                return this._pdu024;
            }
            set
            {
                this._pdu024 = value;
            }
        }
        
        // 
        public string PDU025
        {
            get
            {
                return this._pdu025;
            }
            set
            {
                this._pdu025 = value;
            }
        }
        
        // 
        public string PDU026
        {
            get
            {
                return this._pdu026;
            }
            set
            {
                this._pdu026 = value;
            }
        }
        
        // 
        public string PDU027
        {
            get
            {
                return this._pdu027;
            }
            set
            {
                this._pdu027 = value;
            }
        }
        
        // 
        public string PDU028
        {
            get
            {
                return this._pdu028;
            }
            set
            {
                this._pdu028 = value;
            }
        }
        
        // 
        public string PDU029
        {
            get
            {
                return this._pdu029;
            }
            set
            {
                this._pdu029 = value;
            }
        }
        
        // 
        public string PDU030
        {
            get
            {
                return this._pdu030;
            }
            set
            {
                this._pdu030 = value;
            }
        }
    }
}
