//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterileEntity
{
    using System;
    
    
    public sealed class MaterielPDDEntity
    {
        
        private int _idx;
        
        private string _pdd001;
        
        private string _pdd002;
        
        private string _pdd003;
        
        private string _pdd004;
        
        private string _pdd005;
        
        private int _pdd006;
        
        private string _pdd007;
        
        private string _pdd008;
        
        private string _pdd009;
        
        private DateTime _pdd010;
        
        private string _pdd011;
        
        private string _pdd012;
        
        private string _pdd013;
        
        private string _pdd014;
        
        private string _pdd015;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 安全带款式
        /// </summary>

        public string PDD001
        {
            get
            {
                return this._pdd001;
            }
            set
            {
                this._pdd001 = value;
            }
        }

        /// <summary>
        /// 编号
        /// </summary>

        public string PDD002
        {
            get
            {
                return this._pdd002;
            }
            set
            {
                this._pdd002 = value;
            }
        }

        /// <summary>
        /// 配件类型
        /// </summary>

        public string PDD003
        {
            get
            {
                return this._pdd003;
            }
            set
            {
                this._pdd003 = value;
            }
        }

        /// <summary>
        /// 物料编码
        /// </summary>

        public string PDD004
        {
            get
            {
                return this._pdd004;
            }
            set
            {
                this._pdd004 = value;
            }
        }

        /// <summary>
        /// 物料名称
        /// </summary>

        public string PDD005
        {
            get
            {
                return this._pdd005;
            }
            set
            {
                this._pdd005 = value;
            }
        }

        /// <summary>
        /// 数量
        /// </summary>

        public int PDD006
        {
            get
            {
                return this._pdd006;
            }
            set
            {
                this._pdd006 = value;
            }
        }

        /// <summary>
        /// 配件特点
        /// </summary>

        public string PDD007
        {
            get
            {
                return this._pdd007;
            }
            set
            {
                this._pdd007 = value;
            }
        }

        /// <summary>
        /// 设计稿
        /// </summary>

        public string PDD008
        {
            get
            {
                return this._pdd008;
            }
            set
            {
                this._pdd008 = value;
            }
        }

        /// <summary>
        /// 特别要求
        /// </summary>

        public string PDD009
        {
            get
            {
                return this._pdd009;
            }
            set
            {
                this._pdd009 = value;
            }
        }
        
        // 
        public DateTime PDD010
        {
            get
            {
                return this._pdd010;
            }
            set
            {
                this._pdd010 = value;
            }
        }

        /// <summary>
        /// 合同号
        /// </summary>

        public string PDD011
        {
            get
            {
                return this._pdd011;
            }
            set
            {
                this._pdd011 = value;
            }
        }

        /// <summary>
        /// 品号
        /// </summary>

        public string PDD012
        {
            get
            {
                return this._pdd012;
            }
            set
            {
                this._pdd012 = value;
            }
        }
        
        // 
        public string PDD013
        {
            get
            {
                return this._pdd013;
            }
            set
            {
                this._pdd013 = value;
            }
        }
        
        // 
        public string PDD014
        {
            get
            {
                return this._pdd014;
            }
            set
            {
                this._pdd014 = value;
            }
        }
        
        // 
        public string PDD015
        {
            get
            {
                return this._pdd015;
            }
            set
            {
                this._pdd015 = value;
            }
        }
    }
}
